# Site settings
title: OWASP Madrid Chapter
email: contact<-@->owaspmadrid.org
description: "find events, information and more of OWASP Madrid!"
baseurl: ""
url: "http://owaspmadrid.org"
twitter_username: owaspmadrid
github_username:  owaspmadrid

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

plugins:
  - jekyll-multiple-languages-plugin

languages: ["es", "en"]
exclude_from_localizations: ["static", "CNAME", "LICENSE", "README.md", "sitemap.xml"]
defaultLang: es
languageNames:
  es: Espanol
  en: English